### ISSUE TITLE
str_replace not found

### ISSUE THREAD

**Issue by stemangiola** [stemangiola/bioc_2020_tidytranscriptomics#11]
The test code you gave me

counts_de_pasilla <- tidyHeatmap::pasilla %>%
    mutate(type=str_replace(type, "-", "_")) %>%
    test_differential_abundance(
        .sample=sample,
        .transcript=symbol,
        .abundance=`count normalised adjusted`,
        .formula = ~ 0 + condition + type,
        .contrasts = c("conditiontreated - conditionuntreated"))

use str_replace

however stringr is not in DESCRIPTION library nor suggest

**Comment by mblue9** [comment]
stringr is in the workshop package DESCRIPTION here: https://github.com/stemangiola/bioc_2020_tidytranscriptomics/blob/master/DESCRIPTION#L16
and I have it loaded with library(stringr) then I get that error when I run the code above

**Comment by stemangiola** [comment]
Amazing, I think it should go into DESCRIPTION libraries as well.

Basically all single packages we use should also be mentioned in DESCRIPTION to not give surprises to users.

**Comment by stemangiola** [comment]
Ah OK. I should update my local version then!
