### ISSUE TITLE
Improve exercises

### ISSUE THREAD

**Issue by mblue9** [stemangiola/bioc_2020_tidytranscriptomics#12]
As discussed we should see if we can improve the exercises (the current ones are not final just some to get started)

- [This paper](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1007433) has some good Tips for exercises (below) I think we could try to follow. 

- R for Data Science book is an example of using a variety of exercises e.g. here: https://r4ds.had.co.nz/data-visualisation.html#aesthetic-mappings

For Tip 1 we could aim for ~6 sets of exercises in total for a 2x50 min workshop (think that's the time we've got) where each set takes 1-2 mins. Maybe 2-3 exercises per set - 1 easy, others harder. For Tip 3 we should aim to have a variety of exercise types.

>**Tip 1: Use formative assessment every 10–15 minutes**
Instructors always want to get through more material than time allows, so we often teach at the speed at which we can talk rather than the speed at which people can learn. Having learners do something every 10–15 minutes slows us down to the speed at which people can learn rather than the speed at which we can talk. It also keeps them engaged and gives us and them feedback on whether they have actually understood.

>In-class checks like this are called formative assessments. Good ones take only a minute or two to complete so that they don't derail the flow of the lesson and have an unambiguous correct answer so that they can be checked in large classes. Popular kinds of formative assessment in programming classes include:

>- Answer a multiple choice question.
>- Write a few lines of code.
>- Predict what the code on the screen will do when it runs.
>- Contribute the next line of code.
>- Label a diagram of a data structure.
>- Trace the order in which statements are evaluated.

>Starting with a formative assessment that reviews a previous lesson is a good way to signal that class has started, and having learners recall older material before tackling something new improves learning outcomes [11]. Similarly, ending the class with such an exercise gives learners a sense of how far they have progressed.

>Some formative assessments should be designed in advance; in fact, they should be designed before the lesson content is written so that they can act as goalposts [6]. However, they can also be created on the fly to incorporate and respond to learners' questions and confusions. For example, after writing and presenting a few lines of code, an instructor can ask what would happen if something was added or modified. If learners make different predictions, the instructor can then ask them to debate the outcomes as a form of ad hoc peer instruction [7].

>**Tip 3: Use a variety of exercise types**
The final rule in [7] said, "Don't just code," and it bears elaboration here. Most programming classes rely primarily on code-and-run exercises in which learners write software that behaves in a tightly specified way. To keep learners engaged and to give them opportunities to practice other skills and higher-level reasoning, you should also use the following:

>Parsons Problems, which give them the lines of code needed to solve a problem but in jumbled order [12, 13, 14]. Parsons Problems reduce cognitive load by allowing learners to focus on control flow without simultaneously having to recall syntax.

>Multiple choice questions whose wrong answers have been chosen to probe for specific misconceptions. For example, learners who have worked with spreadsheets may believe that after executing a = 10, b = a, and a = 20, the value of b will be 20.

>Matching and ranking problems in which they match terms from one column to definitions in another, put predefined labels on a diagram, or sort items according to some criteria (e.g., most likely to least likely).

>Debugging, completion, and extension exercises in which learners must fix, finish, or extend an existing program. These all model authentic tasks (i.e., the kinds of things programmers spend most of their time doing in real life).

>Tracing execution order or tracing values, in which the learner lists the order in which the statements in a program are executed or the values that one or more variables take on as the program runs, which are essential program comprehension skills.

>Code reviews in which learners score a program against a marking guide supplied by the instructor in order to learn how to find flaws in code. Learners start with a perfect score and lose points for false positives, as well as false negatives so that they don't simply mark every statement as being wrong in all possible ways.

**Comment by stemangiola** [comment]
I will have a think this week if there is still time. Sorry I'm trying to publish 4 articles that I stardet too long ago and I am if frustration mode :)

**Comment by mblue9** [comment]
No worries, I'll have a think about this too. 4 articles that's a lot! good luck with them

**Comment by mblue9** [comment]
In the end I did not get to add in a variety of exercise types as it's a only short workshop and format is 30 min demo + 25 min activities. Maybe could do that in future versions.
