### ISSUE TITLE
Workshop TODOs

### ISSUE THREAD

**Issue by mblue9** [stemangiola/bioc_2020_tidytranscriptomics#14]
- [x] Update README [https://github.com/stemangiola/bioc_2020_tidytranscriptomics/issues/13 ] 
- [x] Add License
- [x] Add bibliography. Should make a bibliography file with refs like tidyverse, edgeR, 1-2-3 limma papers.
- [x] Maybe add in some comparative examples to show how tidy style can save on writing large code blocks
- [x] Improve exercises [ https://github.com/stemangiola/bioc_2020_tidytranscriptomics/issues/12] 
- [x] Could perhaps have an additional_Info.Rmd file in the vignettes folder with things we won't have time to include but that could be useful to show (e.g. how to use tidybulk if starting from tables of counts & sample information, bar plots, pathway/GO analyses...)
- [x] Shorten to 1 hr & update timings (have shortened it a bit but may need to adjust more)
- [x] Add image at beginning to show RNA-seq workflow & where this fits

**Comment by stemangiola** [comment]
For point 4, I have comparisons in the readme of tidybulk

**Comment by mblue9** [comment]
Am closing this as we're done (yay! )🎉 ..unless we spy anything that needs fixing
