### ISSUE TITLE
bioc2020 tag in Dockerfile doesn't exist

### ISSUE THREAD

**Issue by lwaldron** [stemangiola/bioc_2020_tidytranscriptomics#38]
Need to either create the bioc2020 docker tag on Dockerhub, remove this tag from your Dockerfile, or change the tag to one that exists on Dockerhub (eg bio2020). 

https://github.com/stemangiola/bioc_2020_tidytranscriptomics/blob/05989be48052909bdd76676a309baff4d9a4e8de/DESCRIPTION#L44

**Comment by mblue9** [comment]
Thanks @lwaldron! I've fixed the typo now https://github.com/stemangiola/bioc_2020_tidytranscriptomics/commit/d30da6e476533722c1d03b20286240e065bf3c61
